RplTask and tests
rocketproplab/rpl-task pull request #3
Opened 2023-02-11 23:35 UTC by seanlipps

Implemented RplTask and made unit tests

2023-02-15 02:54 UTC, daftcube requested changes
Looks pretty good. Absolutely great job on a first PR! You should get yourself a milkshake!

I did a quick skim and found a few things. They are _mostly_ nitpicks.

2023-02-15 02:54 UTC, daftcube commented on LinkedListTest.cpp
> +	RplTask* task1 = (RplTask*)new TestTask();
Are these casts necessary?

2023-02-15 02:54 UTC, daftcube commented on LinkedListTest.cpp
> +	RplTask* task1 = (RplTask*)new TestTask();
If not, consider revision to remove unneeded casts across test file.

2023-02-15 02:54 UTC, daftcube commented on RplTaskTest.h
> +		int i = 0;
If we are going to make changes, maybe a comment about what the purpose of this `i` value is :)

2023-02-15 02:54 UTC, daftcube commented on RplTask.cpp
> +	//if (status == CREATED) {
Remove unnecessary code

2023-02-15 02:54 UTC, daftcube commented on RplTask.cpp
> +	//if (status == CREATED) {
Same as on lines 64-66

2023-02-15 02:54 UTC, daftcube commented on RplTask.h
> +    bool checkDepend();
If we are going to make changes, adding comments for all non-constructor/destructor functions in this header would be a good idea.

2023-02-15 02:54 UTC, daftcube commented on TopologicalSort.cpp
> +#include <stdexcept>
We cannot include `stdexcept` as it is part of the standard library.
Instead of exceptions, can we instead return an integer, where code 0 is "good" and other values are exceptions?

2023-02-15 02:54 UTC, daftcube commented on TopologicalSort.cpp
> +#include "TopologialSort.h"
We should probably not be merging these. We will consider deletion for this PR.

2023-02-15 02:54 UTC, daftcube commented on RplTask.h
> +//private:
Consider deletion of unnecessary comments.

2023-02-15 02:54 UTC, daftcube commented on RplTask.cpp
> +	//TODO Whoopsy, error display?
Consider removing unnecessary comments

2023-02-15 02:54 UTC, daftcube commented on LinkedListTest.cpp
> +	RplTask* task1 = new TestTask();
I'm not 100% sure, but I'm worried about a memory leak here. We create `TestTask` instances in the dynamic memory of the test process but never clear them.

While this shouldn't be a showstopper, ensuring the elements are properly cleaned would make this code cleaner.

2023-02-15 08:19 UTC, asbauer commented on LinkedListTest.cpp
> +	RplTask* task1 = new TestTask();
I believe this is handled within the destructor, which should handle the deletion of both the node and the value (which in this case should be task1 for example).

2023-02-18 20:19 UTC, daftcube approved these changes
LGTM :)
but actually though good work, looks good to merge

2023-02-18 20:22 UTC, ZettabytesCode commented on LinkedListTest.cpp
> +	RplTask* task1 = new TestTask();
fixed

2023-02-18 20:28 UTC, ZettabytesCode approved these changes
LGTM

2023-02-18 20:29 UTC, merged